/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.angello.com.view.pages;

import org.angello.com.controller.ControllerVehiculo;
import org.angello.com.model.entities.Vehiculo;

import java.util.ArrayList;

/**
 * @author Deran
 */
public class VehiculosRentados extends View<Vehiculo, ControllerVehiculo> {

    private static VehiculosRentados instance;

    public VehiculosRentados() {
        super(new String[]{"Placa", "Marca", "Color", "Linea", "Tipo Vehiculo"}, "Vehiculo");
    }

    public static VehiculosRentados getInstance() {
        if (instance == null) instance = new VehiculosRentados();
        return instance;
    }

    /**
     * Creates new form VehiculosRentados
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("RentCars page");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 644, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 555, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;

    @Override
    public void render(ArrayList<Vehiculo> vehiculos) {

    }

    @Override
    public ArrayList<ArrayList<String>> modelArrToStringArr2D(ArrayList<Vehiculo> vehiculos) {
        ArrayList<ArrayList<String>> array = new ArrayList<>();

        for (Vehiculo vehiculo : vehiculos) {
            String placa = String.valueOf(vehiculo.getPlaca());
            String marca = String.valueOf(vehiculo.getMarca());
            String color = String.valueOf(vehiculo.getColor());
            String linea = String.valueOf(vehiculo.getLinea());
            String tipoVehiculo = String.valueOf(vehiculo.get_tipoVehiculo());
            array.add(new ArrayList<String>() {{
                add(placa);
                add(marca);
                add(color);
                add(linea);
                add(placa);
                add(tipoVehiculo);
            }});
        }
        return array;
    }

    @Override
    public Vehiculo arrStringToModel(ArrayList<String> tuples) {
        String placa = tuples.get(0);
        String marca = tuples.get(1);
        String color = tuples.get(2);
        String linea = tuples.get(3);
        int tipoVehiculo = Integer.parseInt(tuples.get(4));

        return new Vehiculo(placa, marca, color, linea, tipoVehiculo);
    }

    @Override
    public Vehiculo arrStringToModel(ArrayList<String> tuples, boolean isFormFormat) {
        if (!isFormFormat) return arrStringToModel(tuples);
        Vehiculo vehiculo = arrStringToModel(tuples);
        vehiculo.setPlaca("");

        return vehiculo;
    }
    // End of variables declaration//GEN-END:variables
}
